const TOTAL_COINS = 10000;
const TRANSACTION_FEE = 1;
const TRANSACTION_THRESHOLD = 5;
const FIRST_LEADER = "";
const EPOCH_TIME_IN_MS = 12000;
module.exports = {
  TOTAL_COINS,
  TRANSACTION_FEE,
  TRANSACTION_THRESHOLD,
  FIRST_LEADER,
  EPOCH_TIME_IN_MS,
};
