const TOTAL_COINS = 10000;
const TRANSACTION_FEE = 1;
const INITAL_BALANCE = 100;
const TRANSACTION_THRESHOLD = 5;
const FIRST_LEADER = "";

module.exports = {
  TOTAL_COINS,
  TRANSACTION_FEE,
  INITAL_BALANCE,
  TRANSACTION_THRESHOLD,
  FIRST_LEADER
};